import Form from "@/components/Form";
import prisma from "@/lib/prisma";


const now = new Date();
export const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
};

export default async function Home () {
   
  const User = await prisma.user.findMany();
  
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-100">
      <h1 className="text-4xl font-bold mb-4">Dashboard</h1>
      <p className="text-lg">Welcome to your dashboard!</p>
  <ul >
    {User.map((user)=>(
      <li key={user.id} className="p-4 bg-white shadow rounded mb-2">
        <li className="text-lg font-semibold">{user.name}</li>
        <li className="text-gray-600">{user.email}</li>
      </li>
    ))}
  </ul>
      <div className=" ">
        <Form/>
        </div>
          <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
        <div className="flex flex-center">copyright {years(now)}</div>
      </footer>
    </div>
  );
function years(date: Date) {
  const currentYear = date.getFullYear();
  return currentYear;
}};
